server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/screen
    username: root
    password: 1234
  mvc :
    cors :
      allowed-origins=localhost: 3000
      allowed-methods: GET,POST,PUT,DELETE
      allow-credentials: true

jwt:
  secret: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMQjqSsiCAhz63qCTZF0oHj6W96qslhTcNmXonFZzvkfrnIwQEN7jjMJjFRcK8hifc5fCaGImtO38SIIa9jkpRUCAwEAAQ==
  #access-expireDate: 3600000
  access-expireMillisecond: 3600000   #1000 * 60 * 60 1시간
  refresh-expireMillisecond: 2592000000   #1000 * 60 * 60 * 24 * 30 한달
                      

mybatis:
  type-aliases-package: com.screen.dto	
  mapper-locations: classpath:mapper/*.xml
  
messages:
  basename: i18n/exception
  encoding: UTF-8
  
jpa:
  hibernate:
    ddl-auto: update
  properties:
     hibernate:
       format_sql: true #To beautify or pretty print the SQL
       show_sql: true #show sql

logging:
  level:
    "[org.hibernate]":
      "[type.descriptor.sql]": trace #show parameter binding
      SQL: DEBUG
      